import Report from '../models/Report.js'; import Department from '../models/Department.js'; import { classifyIssue, haversineKm } from '../utils/aiClassifier.js'
export async function createReport(req,res,next){ try{ const ai=classifyIssue({...req.body,imageCount:req.body.images?.length||0}); const dept=await Department.findOne({type:ai.suggestedCategory}); const report=await Report.create({...req.body,submittedBy:req.user?._id,category:req.body.category||ai.suggestedCategory,priorityScore:ai.priorityScore,riskLevel:ai.riskLevel,aiClassification:ai,assignedDepartment:dept?._id,timeline:[{label:'Report submitted',by:req.user?._id},{label:'AI classified issue',by:req.user?._id}]}); res.status(201).json(report)}catch(e){next(e)} }
export async function getReports(req,res,next){ try{ const filter={}; if(req.query.status) filter.status=req.query.status; if(req.query.category) filter.category=req.query.category; const reports=await Report.find(filter).populate('submittedBy','name email trustScore').populate('assignedDepartment','name type district').sort('-createdAt'); res.json(reports)}catch(e){next(e)} }
export async function getReport(req,res,next){ try{ const r=await Report.findById(req.params.id).populate('submittedBy','name email phone trustScore').populate('assignedDepartment','name type district'); if(!r) return res.status(404).json({message:'Report not found'}); res.json(r)}catch(e){next(e)} }
export async function updateStatus(req,res,next){ try{ const r=await Report.findByIdAndUpdate(req.params.id,{$set:{status:req.body.status,resolvedAt:req.body.status==='Resolved'?new Date():undefined},$push:{timeline:{label:req.body.note||`Status updated to ${req.body.status}`,by:req.user?._id}}},{new:true}); res.json(r)}catch(e){next(e)} }
export async function assignReport(req,res,next){ try{ const r=await Report.findByIdAndUpdate(req.params.id,{$set:{assignedDepartment:req.body.departmentId,status:'Assigned'},$push:{timeline:{label:'Assigned to department',by:req.user?._id}}},{new:true}); res.json(r)}catch(e){next(e)} }
export async function addComment(req,res,next){ try{ const r=await Report.findByIdAndUpdate(req.params.id,{$push:{comments:{user:req.user?._id,message:req.body.message,attachments:req.body.attachments||[]}}},{new:true}); res.json(r)}catch(e){next(e)} }
export async function supportReport(req,res,next){ try{ const r=await Report.findByIdAndUpdate(req.params.id,{$addToSet:{supporters:req.user?._id}},{new:true}); res.json(r)}catch(e){next(e)} }
export async function deleteReport(req,res,next){ try{ await Report.findByIdAndDelete(req.params.id); res.json({message:'Report deleted'})}catch(e){next(e)} }
export async function detectDuplicate(req,res,next){ try{ const reports=await Report.find({category:req.body.category,status:{$nin:['Resolved','Closed','Rejected']}}); const duplicates=reports.filter(r=>haversineKm(req.body.location,r.location)<0.7); res.json({duplicates})}catch(e){next(e)} }
