import { Activity, AlertTriangle, CheckCircle2, ClipboardList, Clock, Users } from 'lucide-react'
import StatCard from '../../components/common/StatCard'
import { useAppStore } from '../../store/useAppStore'
import { CategoryChart, StatusPie, TrendChart } from '../../components/charts/Charts'
import ReportTable from '../../components/tables/ReportTable'
import IssueMap from '../../components/map/IssueMap'
export function CitizenDashboard(){ const {reports,user}=useAppStore(); const mine=reports.filter(r=>r.submittedBy===user?.id || user?.role==='citizen'); return <div className="space-y-6"><Header title="Citizen Dashboard" sub="Track your reports, SLA risk and resolution workflow."/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-5"><StatCard icon={ClipboardList} label="My Reports" value={mine.length}/><StatCard icon={Clock} tone="yellow" label="Pending" value={mine.filter(r=>!['Resolved','Closed'].includes(r.status)).length}/><StatCard icon={Activity} label="In Progress" value={mine.filter(r=>r.status==='In Progress').length}/><StatCard icon={CheckCircle2} tone="green" label="Resolved" value={mine.filter(r=>r.status==='Resolved').length}/><StatCard icon={AlertTriangle} label="Critical" value={mine.filter(r=>r.riskLevel==='Critical').length}/></div><div className="grid gap-6 xl:grid-cols-2"><CategoryChart reports={mine}/><StatusPie reports={mine}/></div><ReportTable reports={mine} title="My Civic Reports"/></div> }
export function AdminDashboard(){ const {reports}=useAppStore(); return <div className="space-y-6"><Header title="Admin Command Center" sub="Verify, assign and monitor civic issue resolution."/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><StatCard icon={ClipboardList} label="Total Reports" value={reports.length}/><StatCard icon={AlertTriangle} label="Critical Issues" value={reports.filter(r=>r.riskLevel==='Critical').length}/><StatCard icon={CheckCircle2} tone="green" label="Resolved" value={reports.filter(r=>r.status==='Resolved').length}/><StatCard icon={Clock} tone="yellow" label="Avg Resolution" value="36h"/></div><div className="grid gap-6 xl:grid-cols-2"><TrendChart/><StatusPie reports={reports}/></div><ReportTable reports={reports} title="All Reports"/></div> }
export function AdminReports(){ const {reports}=useAppStore(); return <div className="space-y-6"><Header title="All Reports" sub="Search, filter, verify and assign reports."/><ReportTable reports={reports}/></div> }
export function AdminMap(){ const {reports}=useAppStore(); return <div className="space-y-6"><Header title="Civic Issue Map" sub="Map-based city risk monitoring."/><div className="card"><IssueMap reports={reports}/></div></div> }
export function Analytics(){ const {reports}=useAppStore(); return <div className="space-y-6"><Header title="Analytics & Transparency" sub="Category, status and resolution performance."/><div className="grid gap-6 xl:grid-cols-2"><CategoryChart reports={reports}/><StatusPie reports={reports}/><TrendChart/></div></div> }
export function Departments(){ const {departments}=useAppStore(); return <div className="space-y-6"><Header title="Departments" sub="Smart department routing and public transparency score."/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{departments.map(d=><div className="card" key={d.id}><b>{d.name}</b><p className="mt-2 text-sm text-muted">{d.type} • {d.district}</p><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-2 rounded-full bg-gradient-to-r from-flare to-caution" style={{width:d.transparency+'%'}}/></div><p className="mt-2 text-xs text-muted">Transparency score {d.transparency}%</p></div>)}</div></div> }
export function UsersPage(){ const {users}=useAppStore(); return <div className="space-y-6"><Header title="Users" sub="Role based access demo users."/><div className="card"><table className="w-full text-left text-sm"><thead className="text-muted"><tr><th className="py-3">Name</th><th>Email</th><th>Role</th><th>District</th><th>Trust</th></tr></thead><tbody>{users.map(u=><tr className="border-t border-white/10" key={u.id}><td className="py-4 font-bold">{u.name}</td><td>{u.email}</td><td className="capitalize">{u.role}</td><td>{u.district}</td><td>{u.trustScore||70}%</td></tr>)}</tbody></table></div></div> }
export function DepartmentDashboard(){ const {reports}=useAppStore(); const assigned=reports.filter(r=>r.assignedDepartment); return <div className="space-y-6"><Header title="Department Officer Dashboard" sub="Resolve assigned civic issues and upload proof."/><div className="grid gap-5 md:grid-cols-4"><StatCard icon={ClipboardList} label="Assigned" value={assigned.length}/><StatCard icon={Activity} label="In Progress" value={assigned.filter(r=>r.status==='In Progress').length}/><StatCard icon={CheckCircle2} tone="green" label="Completed" value={assigned.filter(r=>r.status==='Resolved').length}/><StatCard icon={Clock} tone="yellow" label="Avg Completion" value="29h"/></div><ReportTable reports={assigned} title="Assigned Reports"/></div> }
export function Profile(){ const {user}=useAppStore(); return <div className="space-y-6"><Header title="Profile Settings" sub="Citizen account and trust score."/><div className="card max-w-2xl"><div className="grid h-24 w-24 place-items-center rounded-3xl bg-gradient-to-br from-flare to-caution text-4xl font-black text-black">{user?.name?.[0]||'C'}</div><h2 className="mt-5 text-2xl font-black">{user?.name}</h2><p className="text-muted">{user?.email}</p><p className="mt-4 badge border-yellow-400/30 bg-yellow-400/10 text-yellow-300">Civic Trust Score: {user?.trustScore||70}%</p></div></div> }
export function Header({title,sub}){return <div><p className="text-xs uppercase tracking-[.3em] text-caution">CivicFix AI</p><h1 className="text-4xl font-black">{title}</h1><p className="mt-2 text-muted">{sub}</p></div>}
