import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
export function CategoryChart({reports=[]}) {
  const data=Object.entries(reports.reduce((a,r)=>{a[r.category]=(a[r.category]||0)+1;return a},{})).map(([name,value])=>({name,value}))
  return <div className="card"><h3 className="mb-4 font-black">Issues by Category</h3><ResponsiveContainer width="100%" height={250}><BarChart data={data}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.08)"/><XAxis dataKey="name" stroke="#94A3B8" fontSize={11}/><YAxis stroke="#94A3B8"/><Tooltip contentStyle={{background:'#111',border:'1px solid rgba(255,255,255,.1)',borderRadius:16}}/><Bar dataKey="value" radius={[12,12,0,0]} fill="#EF4444"/></BarChart></ResponsiveContainer></div>
}
export function StatusPie({reports=[]}) {
  const data=Object.entries(reports.reduce((a,r)=>{a[r.status]=(a[r.status]||0)+1;return a},{})).map(([name,value])=>({name,value}))
  return <div className="card"><h3 className="mb-4 font-black">Status Distribution</h3><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90} paddingAngle={6}>{data.map((_,i)=><Cell key={i} fill={['#EF4444','#FACC15','#F59E0B','#22C55E','#94A3B8'][i%5]}/>)}</Pie><Tooltip contentStyle={{background:'#111',border:'1px solid rgba(255,255,255,.1)',borderRadius:16}}/></PieChart></ResponsiveContainer></div>
}
export function TrendChart(){ const data=['Jan','Feb','Mar','Apr','May','Jun'].map((m,i)=>({m, reports:120+i*42+Math.round(Math.random()*25), resolved:80+i*35})); return <div className="card"><h3 className="mb-4 font-black">Resolution Trend</h3><ResponsiveContainer width="100%" height={250}><AreaChart data={data}><defs><linearGradient id="r" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#EF4444" stopOpacity={.55}/><stop offset="95%" stopColor="#EF4444" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.08)"/><XAxis dataKey="m" stroke="#94A3B8"/><YAxis stroke="#94A3B8"/><Tooltip contentStyle={{background:'#111',border:'1px solid rgba(255,255,255,.1)',borderRadius:16}}/><Area type="monotone" dataKey="reports" stroke="#EF4444" fill="url(#r)"/><Area type="monotone" dataKey="resolved" stroke="#FACC15" fill="rgba(250,204,21,.12)"/></AreaChart></ResponsiveContainer></div> }
