import { Navigate, Route, Routes } from 'react-router-dom'
import Landing from './pages/public/Landing'
import Login from './pages/auth/Login'
import Register from './pages/auth/Register'
import DashboardLayout from './components/layout/DashboardLayout'
import SubmitReport from './pages/citizen/SubmitReport'
import ReportDetail from './pages/reports/ReportDetail'
import { AdminDashboard, AdminMap, AdminReports, Analytics, CitizenDashboard, DepartmentDashboard, Departments, Header, Profile, UsersPage } from './pages/dashboards/DashboardPages'
import { PublicMap, Transparency } from './pages/public/PublicPages'
import { useAppStore } from './store/useAppStore'
function Protected({children, roles}){ const user=useAppStore(s=>s.user); if(!user) return <Navigate to="/login"/>; if(roles && !roles.includes(user.role)) return <Navigate to="/unauthorized"/>; return children }
function RoleHome(){ const user=useAppStore(s=>s.user); if(user?.role==='admin') return <Navigate to="/admin"/>; if(user?.role==='department') return <Navigate to="/department"/>; return <CitizenDashboard/> }
export default function App(){ return <Routes><Route path="/" element={<Landing/>}/><Route path="/public-map" element={<PublicMap/>}/><Route path="/transparency" element={<Transparency/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route element={<Protected><DashboardLayout/></Protected>}><Route path="/dashboard" element={<RoleHome/>}/><Route path="/submit" element={<SubmitReport/>}/><Route path="/my-reports" element={<CitizenDashboard/>}/><Route path="/profile" element={<Profile/>}/><Route path="/reports/:id" element={<ReportDetail/>}/><Route path="/admin" element={<Protected roles={['admin']}><AdminDashboard/></Protected>}/><Route path="/admin/reports" element={<Protected roles={['admin']}><AdminReports/></Protected>}/><Route path="/admin/map" element={<Protected roles={['admin']}><AdminMap/></Protected>}/><Route path="/admin/analytics" element={<Protected roles={['admin']}><Analytics/></Protected>}/><Route path="/admin/departments" element={<Protected roles={['admin']}><Departments/></Protected>}/><Route path="/admin/users" element={<Protected roles={['admin']}><UsersPage/></Protected>}/><Route path="/department" element={<Protected roles={['department']}><DepartmentDashboard/></Protected>}/><Route path="/department/assigned" element={<Protected roles={['department']}><DepartmentDashboard/></Protected>}/><Route path="/department/performance" element={<Protected roles={['department']}><Analytics/></Protected>}/></Route><Route path="/unauthorized" element={<div className="min-h-screen bg-ink p-10"><div className="card mx-auto max-w-xl"><Header title="Unauthorized" sub="You do not have permission to access this route."/></div></div>}/><Route path="*" element={<div className="min-h-screen bg-ink p-10"><div className="card mx-auto max-w-xl"><Header title="404 Not Found" sub="This page does not exist."/></div></div>}/></Routes> }
